CREATE TABLE `demo` (
  `seq` INT(11) NOT NULL AUTO_INCREMENT COMMENT '번호',
  `name` VARCHAR(50) NOT NULL COMMENT '이름',
  `age` INT(11) NULL DEFAULT NULL COMMENT '나이',
  `hobby` VARCHAR(50) NULL DEFAULT NULL COMMENT '취미',
  PRIMARY KEY (`seq`)
);

CREATE TABLE `access` (
	`access_seq` INT(11) NOT NULL AUTO_INCREMENT,
	`access_url` VARCHAR(50) NOT NULL,
	`access_role` VARCHAR(10) NOT NULL,
	`reg_id` VARCHAR(20) NULL DEFAULT NULL,
	`reg_nm` VARCHAR(50) NULL DEFAULT NULL,
	`reg_dt` DATETIME NULL DEFAULT NULL,
	`mod_id` VARCHAR(20) NULL DEFAULT NULL,
	`mod_nm` VARCHAR(50) NULL DEFAULT NULL,
	`mod_dt` DATETIME NULL DEFAULT NULL,
	`del_yn` CHAR(50) NULL DEFAULT 'N',
	PRIMARY KEY (`access_seq`)
);


CREATE TABLE `access_role` (
	`access_url` VARCHAR(50) NOT NULL,
	`access_role` CHAR(10) NOT NULL,
	`reg_id` VARCHAR(20) NULL DEFAULT NULL,
	`reg_nm` VARCHAR(50) NULL DEFAULT NULL,
	`reg_dt` DATETIME NULL DEFAULT NULL,
	`mod_id` VARCHAR(20) NULL DEFAULT NULL,
	`mod_nm` VARCHAR(50) NULL DEFAULT NULL,
	`mod_dt` DATETIME NULL DEFAULT NULL,
	`del_yn` CHAR(50) NULL DEFAULT 'N',
	UNIQUE INDEX `UNIQUE KEY` (`access_url`, `access_role`)
);



CREATE TABLE `role` (
	`role_seq` INT(11) NOT NULL AUTO_INCREMENT,
	`role_code` CHAR(5) NOT NULL,
	`role_name` VARCHAR(20) NOT NULL,
	`reg_id` VARCHAR(20) NULL DEFAULT NULL,
	`reg_nm` VARCHAR(50) NULL DEFAULT NULL,
	`reg_dt` DATETIME NULL DEFAULT NULL,
	`mod_id` VARCHAR(20) NULL DEFAULT NULL,
	`mod_nm` VARCHAR(50) NULL DEFAULT NULL,
	`mod_dt` DATETIME NULL DEFAULT NULL,
	`del_yn` CHAR(50) NULL DEFAULT 'N',
	PRIMARY KEY (`role_seq`)
);


CREATE TABLE `access` (
	`access_seq` INT(11) NOT NULL AUTO_INCREMENT,
	`access_url` VARCHAR(50) NOT NULL,
	`access_role` VARCHAR(10) NOT NULL,
	`reg_id` VARCHAR(20) NULL DEFAULT NULL,
	`reg_nm` VARCHAR(50) NULL DEFAULT NULL,
	`reg_dt` DATETIME NULL DEFAULT NULL,
	`mod_id` VARCHAR(20) NULL DEFAULT NULL,
	`mod_nm` VARCHAR(50) NULL DEFAULT NULL,
	`mod_dt` DATETIME NULL DEFAULT NULL,
	`del_yn` CHAR(50) NULL DEFAULT 'N',
	PRIMARY KEY (`access_seq`)
);

CREATE TABLE `access_role` (
	`access_url` VARCHAR(50) NOT NULL,
	`access_role` CHAR(10) NOT NULL,
	`reg_id` VARCHAR(20) NULL DEFAULT NULL,
	`reg_nm` VARCHAR(50) NULL DEFAULT NULL,
	`reg_dt` DATETIME NULL DEFAULT NULL,
	`mod_id` VARCHAR(20) NULL DEFAULT NULL,
	`mod_nm` VARCHAR(50) NULL DEFAULT NULL,
	`mod_dt` DATETIME NULL DEFAULT NULL,
	`del_yn` CHAR(50) NULL DEFAULT 'N',
	UNIQUE INDEX `UNIQUE KEY` (`access_url`, `access_role`)
);



CREATE TABLE `persistent_logins` (
  `username` varchar(64) DEFAULT NULL,
  `series` varchar(64) NOT NULL,
  `token` varchar(64) DEFAULT NULL,
  `last_used` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`series`)
);